import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from "react";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    const [phoneNumber, setPhoneNumber] = useState('');
    const [submitButtonDisabled, setSubmitButtonDisabled] = useState(true);
    const [errors, setErrors] = useState(['Phone number must be a number']);

    function validatePhoneNumber(value) {
        const regex = /[0-9]+/
        if (regex.test(value)) {
            setSubmitButtonDisabled(false);
            setPhoneNumber(value);
            setErrors([]);
        } else {
            setSubmitButtonDisabled(true);
            setPhoneNumber('');
            setErrors(['Phone number must be a number']);
        }
    }

    return (
        <>
            <Head>
                <title>Form validation</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.main}>
                <div className={styles.description}>
                    <p>
                        Official Drain Licensed Product © 2023&nbsp;
                    </p>
                </div>
                <form className={styles.form}>

                    <div className={styles.formGroup}>
                        <label htmlFor="name">Name</label>
                        <input type="text" id="name" name="name"/>
                    </div>

                    <div className={styles.formGroup}>
                        <label htmlFor="phone_number">Phone Number</label>
                        <input type="text" id="phone_number" name="phone_number" value={phoneNumber}
                               onChange={(e) => validatePhoneNumber(e.target.value)}
                               className={phoneNumber === '' ? styles.invalidPhoneNumber : styles.validPhoneNumber}/>
                        <p>
                            {errors.map((error, index) => (
                                <span key={index} className={styles.error}>{error}</span>
                            ))}
                        </p>
                    </div>
                    <button type="submit" disabled={submitButtonDisabled}>Submit</button>
                </form>
            </div>
        </>
    )
}
